# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="dantas"
DISABLE_AUTO_UPDATE=true # disables ZSH autoupdate

plugins=(git osx autojump)

source $ZSH/oh-my-zsh.sh
source ~/.dotfiles/alias.sh
source ~/.dotfiles/export.sh
source ~/.dotfiles/vendor/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# It will enable to use cd -1, cd -2 to go back to previous folders
setopt AUTO_PUSHD

# Init the fasd
eval "$(fasd --init auto)"

# It will do a ls after a cd
function chpwd() {
    emulate -L zsh
    ls
}

# Enables the edition of command lines!
# press cltr+x cltr+e to open the editor and fix any command line errors
autoload edit-command-line
zle -N edit-command-line
bindkey '^X^E' edit-command-line
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

# starscream env setup:
export WORKON_HOME=~/.virtualenvs
source $(brew --prefix)/bin/virtualenvwrapper.sh
