# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="dantas"

plugins=(git osx autojump)

source $ZSH/oh-my-zsh.sh
source ~/.dotfiles/alias.sh
source ~/.dotfiles/export.sh

# Loading RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# It will enable to use cd -1, cd -2 to go back to previous folders
setopt AUTO_PUSHD

# Init the fasd
eval "$(fasd --init auto)"

# It will do a ls after a cd
function chpwd() {
    emulate -L zsh
    ls
}

# Enables the edition of command lines!
# press cltr+x cltr+e to open the editor and fix any command line errors
autoload edit-command-line
zle -N edit-command-line
bindkey '^X^E' edit-command-line
